import Link from "next/link";
import { ArrowLeft, Braces, CircleAlert, FileCode2, GitCommitHorizontal, ShieldCheck } from "lucide-react";
import { ArtifactActions } from "@/components/extensions/artifact-actions";
import { requireCompanyId } from "@/lib/auth/company";
import { prisma } from "@/lib/db/client";
import { ExtensionRepository } from "@/lib/db/extensions";

const states: Record<string, string> = { uploaded: "bg-[#27325a] text-[#b9c8ff]", evaluating: "bg-[#3e3320] text-[#ffd995]", deployable: "bg-[#173d2b] text-[#a6efca]", evaluation_failed: "bg-[#4b272b] text-[#ffb6b6]", runtime_unsupported: "bg-[#342b42] text-[#d7bcff]", healthy: "bg-[#173d2b] text-[#a6efca]", finding: "bg-[#4d3520] text-[#ffd08a]", failed: "bg-[#4b272b] text-[#ffb6b6]" };
const stamp = (value: Date | null | undefined) => value ? value.toLocaleString() : "—";

export default async function ArtifactDetailPage({ params }: { params: Promise<{ artifactId: string }> }) {
  const { artifactId } = await params;
  let artifact: Awaited<ReturnType<ExtensionRepository["findArtifact"]>> = null;
  let failure: string | undefined;
  try { artifact = await new ExtensionRepository(prisma).findArtifact(requireCompanyId(), artifactId); } catch (error) { failure = error instanceof Error ? error.message : "Artifact is unavailable"; }
  if (!artifact) return <main className="grid min-h-screen place-items-center bg-[#080b10] p-6 text-[#e8edf7]"><div className="max-w-md rounded-2xl border border-[#3a2930] bg-[#171116] p-6"><CircleAlert className="text-[#ffabab]" /><h1 className="mt-4 text-xl font-semibold">Artifact unavailable</h1><p className="mt-2 text-sm leading-6 text-[#c7aeb3]">{failure ?? "This artifact does not exist in the current company."}</p><Link href="/extensions" className="mt-5 inline-flex text-sm text-[#b9c8ff]">Return to registry</Link></div></main>;
  const manifest = artifact.manifest as { version: string; description: string; implementation: { language: string; runtime: string; entrypoint: string }; deployment: { schedule: string }; commands: Record<string, string> };
  const evaluation = artifact.evaluations[0];
  const deployment = artifact.deployments[0];
  const runs = deployment?.runs ?? [];
  return <main className="min-h-screen bg-[#080b10] px-5 py-8 text-[#eef1f6] sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl">
    <Link href="/extensions" className="mb-8 inline-flex items-center gap-2 text-sm text-[#a4b4da] hover:text-[#d8e2ff]"><ArrowLeft size={16} />Artifact registry</Link>
    <header className="rounded-2xl border border-[#2d3544] bg-[linear-gradient(110deg,#121826,#0f131b_54%,#101419)] p-6 shadow-[0_24px_70px_rgba(0,0,0,.22)] sm:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs tracking-[.16em] text-[#91a5ef]">IMMUTABLE ARTIFACT</p><span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${states[artifact.state]}`}>{artifact.state.replace("_", " ")}</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight">{artifact.extension.name}</h1><p className="mt-2 text-sm text-[#aab4c5]">{manifest.description} · v{manifest.version}</p><div className="mt-6 rounded-xl border border-[#303b50] bg-[#0a0e15] p-4"><p className="text-[11px] font-medium uppercase tracking-[.14em] text-[#7786a6]">Extension tracking ID</p><p className="mt-2 break-all font-mono text-sm leading-6 text-[#d6e0ff]">{artifact.sha256}</p></div></div><ArtifactActions artifactId={artifact.id} state={artifact.state} deployment={deployment ? { id: deployment.id, status: deployment.status } : undefined} /></div></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,.9fr)]"><div className="space-y-6">
      <section className="rounded-2xl border border-[#252c38] bg-[#0e1219]"><SectionTitle icon={<FileCode2 size={17} />} title="Artifact contract" /><dl className="grid gap-px bg-[#252c38] sm:grid-cols-2">{[["Adapter", artifact.adapterKey ?? "Unsupported"],["Language", `${manifest.implementation.language} · ${manifest.implementation.runtime}`],["Entrypoint", manifest.implementation.entrypoint],["Schedule", manifest.deployment.schedule],["Stored size", `${artifact.size.toLocaleString()} bytes`],["Stored", stamp(artifact.createdAt)]].map(([key, value]) => <div key={key} className="bg-[#0e1219] px-4 py-3"><dt className="text-xs text-[#7f8b9f]">{key}</dt><dd className="mt-1 font-mono text-sm text-[#dce3f1]">{value}</dd></div>)}</dl></section>
      <section className="rounded-2xl border border-[#252c38] bg-[#0e1219]"><SectionTitle icon={<GitCommitHorizontal size={17} />} title="Latest evaluation" />{evaluation ? <div className="p-5"><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${states[evaluation.status === "passed" ? "deployable" : "evaluation_failed"]}`}>{evaluation.status}</span><span className="text-sm text-[#98a4b8]">Started {stamp(evaluation.startedAt)}</span></div><p className="mt-4 text-sm text-[#c0c9d8]">{evaluation.status === "passed" ? "Preflight was silent and every lifecycle command exited successfully." : "Preflight evidence is retained below; this artifact cannot be deployed."}</p><CommandEvidence evidence={evaluation.commandResults} /></div> : <Empty label="No preflight has been queued for this artifact." />}</section>
      <section className="rounded-2xl border border-[#252c38] bg-[#0e1219]"><SectionTitle icon={<ShieldCheck size={17} />} title="Runs and findings" />{runs.length ? <div className="divide-y divide-[#252c38]">{runs.map((run) => <div key={run.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium text-[#e4eaf5]">Due {stamp(run.dueAt)}</p><p className="mt-1 text-xs text-[#8490a4]">Exit {run.exitCode ?? "—"} · finished {stamp(run.finishedAt)}</p></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${states[run.status]}`}>{run.status}</span></div>{run.findings.map((finding) => <details key={finding.id} className="mt-3 rounded-lg border border-[#574127] bg-[#1d1710] p-3"><summary className="cursor-pointer text-sm text-[#ffd494]">{finding.severity}: {finding.title}</summary><pre className="mt-3 overflow-auto text-xs leading-5 text-[#d8c8ad]">{JSON.stringify(finding.envelope, null, 2)}</pre></details>)}</div>)}</div> : <Empty label="No scheduled run has completed yet." />}</section>
    </div><aside className="space-y-6"><section className="rounded-2xl border border-[#252c38] bg-[#0e1219]"><SectionTitle icon={<Braces size={17} />} title="Declared lifecycle" /><div className="space-y-3 p-5">{Object.entries(manifest.commands).filter(([name]) => ["install", "build", "run"].includes(name)).map(([name, command]) => <div key={name}><p className="mb-1 text-xs capitalize text-[#7f8b9f]">{name}</p><code className="block overflow-x-auto rounded-lg border border-[#263044] bg-[#090d14] p-3 text-xs text-[#b9c8ff]">{command}</code></div>)}</div></section><section className="rounded-2xl border border-[#252c38] bg-[#0e1219]"><SectionTitle icon={<ShieldCheck size={17} />} title="Deployment" />{deployment ? <div className="p-5"><p className="font-medium text-[#e6edf8]">{deployment.status} · {deployment.schedule}</p><p className="mt-2 text-sm text-[#98a4b8]">Next due {stamp(deployment.nextRunAt)}</p></div> : <Empty label="A passing preflight can create one deployment from this manifest schedule." />}</section></aside></div>
  </div></main>;
}

function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-2 border-b border-[#252c38] px-5 py-4 text-sm font-semibold text-[#e8edf7]"><span className="text-[#91a5ef]">{icon}</span>{title}</div>; }
function Empty({ label }: { label: string }) { return <p className="p-5 text-sm leading-6 text-[#8490a4]">{label}</p>; }
function CommandEvidence({ evidence }: { evidence: unknown }) { if (!evidence) return null; return <details className="mt-4 rounded-lg border border-[#273044] bg-[#0a0e15] p-3"><summary className="cursor-pointer text-sm text-[#afbdd9]">Inspect command evidence</summary><pre className="mt-3 overflow-auto text-xs leading-5 text-[#a7b5d1]">{JSON.stringify(evidence, null, 2)}</pre></details>; }
